package:
  name: cfanalytics
  version: "0.1.0"

source:
  git_rev: v0.1.0
  git_url: https://github.com/raybellwaves/cfanalytics.git

requirements:
  build:
    - python
    - setuptools
    - requests
    - aiohttp
    - pandas
  run:
    - python

test:
  imports:
    - cfanalytics

about:
  home: https://github.com/raybellwaves/cfanalytics
  license: BSD
  license_file: LICENSE
